version: "3.9"
services:
  # Mongo Database
  mongo-service:
    image: mongo:5.0
    container_name: delivery-gateway-MongoDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  # Spring-Boot API
  api_service:
    image: paradocx96/delivery-gateway-api:v1
    container_name: delivery-gateway-api
    build:
      context: ../..
      dockerfile: ../../Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongo-service
