apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: delivery-gateway
data:
  mongo-url: mongo-service
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: delivery-gateway
type: Opaque
data:
  mongo-user: cm9vdA==
  mongo-password: cm9vdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: delivery-gateway
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: delivery-gateway
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

