on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: it19180526.azurecr.io
        username: ${{ secrets.acr_it19180526_username }}
        password: ${{ secrets.acr_it19180526_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/app" -f  "Dockerfile" -t it19180526.azurecr.io/ctsecluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push it19180526.azurecr.io/ctsecluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_ctsecluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default-1652276539721 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default-1652276539721`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default-1652276539721
        container-registry-url: it19180526.azurecr.io
        container-registry-username: ${{ secrets.acr_it19180526_username }}
        container-registry-password: ${{ secrets.acr_it19180526_password }}
        secret-name: ctseclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default-1652276539721
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          it19180526.azurecr.io/ctsecluster:${{ github.sha }}
        imagepullsecrets: |
          ctseclusterdockerauth
